import createClient, {
  type ClientOptions,
  wrapAsPathBasedClient,
} from "openapi-fetch";
import type { paths, components } from "./__generated/revenuecat-api-v2"; // generated by openapi-typescript

export type { paths, components };

export type CreateRevenueCatClientOptions = ClientOptions;

const defaultOptions: CreateRevenueCatClientOptions = {
  baseUrl: "https://api.revenuecat.com/v2",
};

export function createRevenueCatClient(
  accessToken: string,
  options?: CreateRevenueCatClientOptions,
) {
  if (!accessToken) {
    // For non-TS users, we'll throw an error if the accessToken is not provided
    throw new Error("accessToken is required");
  }

  const { headers, ...otherOptions } = {
    ...defaultOptions,
    ...options,
  };

  const client = createClient<paths>({
    ...otherOptions,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      ...headers,
    },
  });

  const pathBasedClient = wrapAsPathBasedClient(client);

  return pathBasedClient;
}
